# -*- coding: utf-8 -*-
"""Practical 9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KSIbQwuSi4xEYqPZwFgF-jwl7FON_S_A
"""

# Prim's Algorithm

# Number of vertices
n = int(input("Enter the number of vertices: "))

# Input adjacency matrix
print("Enter the adjacency matrix:")
print("Enter 0 if there is no edge.")

graph = []

for i in range(n):
    row = list(map(int, input(f"Row {i + 1}: ").split()))
    graph.append(row)

# Array to keep track of selected vertices
selected = [False] * n

# Start from vertex 0
selected[0] = True

total_cost = 0

print("\nMinimum Spanning Tree:")

# MST contains n-1 edges
for _ in range(n - 1):

    minimum = float('inf')
    x = -1
    y = -1

    # Find the minimum weight edge
    for i in range(n):
        if selected[i]:
            for j in range(n):
                if not selected[j] and graph[i][j] != 0:
                    if graph[i][j] < minimum:
                        minimum = graph[i][j]
                        x = i
                        y = j

    # Select the new vertex
    selected[y] = True

    print(f"Vertex {x + 1} - Vertex {y + 1} : Weight = {minimum}")

    total_cost += minimum

print("\nTotal cost of Minimum Spanning Tree:", total_cost)