# -*- coding: utf-8 -*-
"""practical 8 daa

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n2Hgh5eW3coYaA4DO0nX-EkCJokJmqWv
"""

from collections import deque

# Get number of vertices
n = int(input("Enter the number of vertices: "))

# Create graph using adjacency list
graph = {}

for i in range(n):
    graph[i] = []

# Get number of edges
e = int(input("Enter the number of edges: "))

# Get edges
print("Enter the edges (u v):")
for _ in range(e):
    u, v = map(int, input().split())
    graph[u].append(v)
    graph[v].append(u)   # Remove this line for a directed graph

# Display graph
print("\nGraph:")
for vertex in graph:
    print(vertex, "->", graph[vertex])


# ---------------- DFS ----------------
def dfs(graph, start, visited=None):
    if visited is None:
        visited = set()

    visited.add(start)
    print(start, end=" ")

    for neighbor in graph[start]:
        if neighbor not in visited:
            dfs(graph, neighbor, visited)


# ---------------- BFS ----------------
def bfs(graph, start):
    visited = set()
    queue = deque([start])
    visited.add(start)

    while queue:
        vertex = queue.popleft()
        print(vertex, end=" ")

        for neighbor in graph[vertex]:
            if neighbor not in visited:
                visited.add(neighbor)
                queue.append(neighbor)


# Starting vertex
start = int(input("\nEnter the starting vertex: "))

# Perform DFS
print("\nDFS Traversal:")
dfs(graph, start)

# Perform BFS
print("\nBFS Traversal:")
bfs(graph, start)